// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLj-tMSsCbCVRNE0WI1aM2Wi0kU2D8sU',
    appId: '1:464577797808:web:5d01a0b8bd30d702c2e575',
    messagingSenderId: '464577797808',
    projectId: 'just-food-amentware',
    authDomain: 'just-food-amentware.firebaseapp.com',
    storageBucket: 'just-food-amentware.appspot.com',
    measurementId: 'G-C7EX5CNETG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJl9ei4tf07m1M-CURWTu2YTOVypC9lw',
    appId: '1:464577797808:android:81ec81e1637edc57c2e575',
    messagingSenderId: '464577797808',
    projectId: 'just-food-amentware',
    storageBucket: 'just-food-amentware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuh6uoES1bj6KlmPtbyC4mTHCoKdW9TI',
    appId: '1:464577797808:ios:7f3babb816ff1864c2e575',
    messagingSenderId: '464577797808',
    projectId: 'just-food-amentware',
    storageBucket: 'just-food-amentware.appspot.com',
    iosClientId: '464577797808-qg1krhv0q14re5mi1k937f23f8d92994.apps.googleusercontent.com',
    iosBundleId: 'com.example.justFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuh6uoES1bj6KlmPtbyC4mTHCoKdW9TI',
    appId: '1:464577797808:ios:7f3babb816ff1864c2e575',
    messagingSenderId: '464577797808',
    projectId: 'just-food-amentware',
    storageBucket: 'just-food-amentware.appspot.com',
    iosClientId: '464577797808-qg1krhv0q14re5mi1k937f23f8d92994.apps.googleusercontent.com',
    iosBundleId: 'com.example.justFood',
  );
}
